# Generated by Django 4.1 on 2022-08-16 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_poupanca'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poupanca',
            options={'verbose_name': 'Poupança', 'verbose_name_plural': 'Poupança'},
        ),
    ]
